name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  continuous:
    name: Continuous Deploy

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          path-type: inherit
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-libusb
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - uses: actions/checkout@v2
      - name: go get
        run: go get
      - name: go build
        run: go build -v -o netmd-cli

      - name: publish
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/enimatek-nl/go-netmd-cli/releases/43283885/assets{?name,label}
          release_id: 43283885
          asset_path: ./netmd-cli
          asset_name: netmd-cli-windows-amd64
          asset_content_type: application/octet-stream
          max_releases: 1